const fs = require('fs');
const path = require('path');

const categories = {
  animali: [
    "Cane", "Gatto", "Topo", "Elefante", "Leone", "Tigre", "Giraffa", "Scimmia", "Orso", "Panda", "Koala", "Canguro", "Rinoceronte", "Ippopotamo", "Zebra", "Cavallo", "Asino", "Mucca", "Maiale", "Pecora", "Capra", "Coniglio", "Lupo", "Volpe", "Cervo", "Scoiattolo", "Castoro", "Pipistrello", "Aquila", "Falco", "Gufo", "Pappagallo", "Gabbiano", "Piccione", "Corvo", "Cigno", "Anatra", "Oca", "Pinguino", "Struzzo", "Pavone", "Fenicottero", "Tucano", "Colibri", "Serpente", "Lucertola", "Iguana", "Camaleonte", "Coccodrillo", "Alligatore", "Tartaruga", "Rana", "Rospo", "Salamandra", "Pesce rosso", "Squalo", "Balena", "Delfino", "Orca", "Polpo", "Calamaro", "Medusa", "Stella marina", "Granchio", "Aragosta", "Gambero", "Cavalluccio marino", "Ragno", "Scorpione", "Millepiedi", "Farfalla", "Falena", "Ape", "Vespa", "Formica", "Mosca", "Zanzara", "Libellula", "Cicala", "Grillo", "Cavalletta", "Mantide", "Coccinella", "Scarabeo", "Lombrico", "Lumaca", "Chiocciola", "Tricheco", "Foca", "Lontra", "Castoro", "Tasso", "Moffetta", "Istrice", "Riccio", "Talpa", "Bradipo", "Armadillo", "Formichiere", "Tapiro", "Lama", "Alpaca", "Cammello", "Dromedario", "Yak", "Bufalo", "Bisonte", "Alce", "Renna", "Ghepardo", "Leopardo", "Pantera", "Puma", "Lince", "Iena", "Sciacallo", "Dingo", "Coyote", "Tricheco", "Narvalo", "Beluga", "Capodoglio", "Manta", "Razza", "Anguilla", "Murena", "Piranha", "Pesce palla", "Pesce spada", "Marlin", "Tonno", "Salmone", "Trota", "Carpa", "Luccio", "Pesce gatto", "Storione", "Caviale"
  ],
  oggetti: [
    "Sedia", "Tavolo", "Divano", "Letto", "Armadio", "Comodino", "Libreria", "Scrivania", "Lampada", "Tappeto", "Quadro", "Orologio", "Specchio", "Cuscino", "Coperta", "Lenzuolo", "Asciugamano", "Accappatoio", "Spazzolino", "Dentifricio", "Sapone", "Shampoo", "Bagnoschiuma", "Spugna", "Pettine", "Spazzola", "Phon", "Rasoio", "Profumo", "Deodorante", "Trucco", "Rossetto", "Smalto", "Forbici", "Tagliaunghie", "Pinzette", "Occhiali", "Lenti a contatto", "Ombrello", "Borsa", "Zaino", "Valigia", "Portafoglio", "Chiavi", "Portachiavi", "Cellulare", "Computer", "Tablet", "Televisione", "Telecomando", "Stereo", "Cuffie", "Auricolari", "Caricabatterie", "Cavo", "Presa", "Interruttore", "Lampadina", "Batteria", "Libro", "Quaderno", "Diario", "Agenda", "Penna", "Matita", "Gomma", "Temperamatite", "Righello", "Squadra", "Compasso", "Evidenziatore", "Pennarello", "Pastello", "Pennello", "Tavolozza", "Colori", "Tela", "Cavalletto", "Macchina fotografica", "Videocamera", "Trepiede", "Bicicletta", "Skateboard", "Pattini", "Monopattino", "Automobile", "Motocicletta", "Casco", "Ruota", "Pneumatico", "Volante", "Cambio", "Freno", "Acceleratore", "Specchietto", "Cintura", "Airbag", "Tergicristallo", "Faro", "Clacson", "Targa", "Chiave inglese", "Cacciavite", "Martello", "Pinza", "Sega", "Trapano", "Chiodo", "Vite", "Bullone", "Dado", "Rondella", "Metro", "Livella", "Pialla", "Scalpello", "Morsa", "Saldatore", "Colla", "Nastro adesivo", "Corda", "Spago", "Filo", "Ago", "Spillo", "Bottone", "Cerniera", "Forbici da sarta", "Ditale", "Macchina da cucire", "Ferro da stiro", "Asse da stiro", "Stendino", "Molletta", "Bacinella", "Secchio", "Scopa", "Paletta", "Mocio", "Aspirapolvere", "Pattumiera", "Sacchetto", "Spolverino", "Straccio", "Spugna", "Detersivo", "Candeggina", "Ammoniaca", "Sgrassatore", "Insetticida", "Antitarlo", "Deodorante ambiente"
  ],
  cibo_cucina: [
    "Piatto", "Bicchiere", "Tazza", "Tazzina", "Posata", "Forchetta", "Coltello", "Cucchiaio", "Cucchiaino", "Pentola", "Padella", "Tegame", "Casseruola", "Coperchio", "Mestolo", "Schiumarola", "Spatola", "Frusta", "Mattarello", "Tagliere", "Grattugia", "Scolapasta", "Imbuto", "Colino", "Spremiagrumi", "Schiaccianoci", "Cavatappi", "Apribottiglie", "Apriscatole", "Pelapatate", "Macinapepe", "Macinacaffè", "Bilancia", "Caraffa", "Brocca", "Bottiglia", "Vaso", "Barattolo", "Scatola", "Busta", "Sacchetto", "Vassoio", "Sottopentola", "Tovaglia", "Tovagliolo", "Presina", "Guanto da forno", "Grembiule", "Forno", "Fornello", "Microonde", "Frigorifero", "Congelatore", "Lavastoviglie", "Tostapane", "Frullatore", "Impastatrice", "Macchina del caffè", "Bollitore", "Moka", "Teiera", "Termos", "Bistecchiera", "Piastra", "Griglia", "Barbecue", "Spiedo", "Pizza", "Pasta", "Pane", "Riso", "Carne", "Pesce", "Uovo", "Formaggio", "Latte", "Burro", "Olio", "Aceto", "Sale", "Pepe", "Zucchero", "Farina", "Lievito", "Cioccolato", "Caffè", "Tè", "Vino", "Birra", "Acqua", "Succo", "Frutta", "Verdura", "Mela", "Pera", "Banana", "Arancia", "Limone", "Fragola", "Ciliegia", "Uva", "Pesca", "Albicocca", "Prugna", "Fico", "Mandarino", "Pompelmo", "Melone", "Anguria", "Ananas", "Kiwi", "Mango", "Papaya", "Noce", "Nocciola", "Mandorla", "Pistacchio", "Arachide", "Castagna", "Pomodoro", "Patata", "Carota", "Cipolla", "Aglio", "Sedano", "Zucchina", "Melanzana", "Peperone", "Insalata", "Spinaci", "Cavolo", "Broccolo", "Cavolfiore", "Zucca", "Carciofo", "Fungo", "Tartufo", "Fagiolo", "Pisello", "Cece", "Lenticchia", "Mais", "Grano", "Orzo", "Farro", "Avena"
  ],
  luoghi_natura: [
    "Montagna", "Collina", "Pianura", "Valle", "Fiume", "Lago", "Mare", "Oceano", "Spiaggia", "Scogliera", "Isola", "Penisola", "Golfo", "Baia", "Stretto", "Canale", "Cascata", "Ghiacciaio", "Vulcano", "Grotta", "Caverna", "Deserto", "Oasi", "Duna", "Foresta", "Bosco", "Selva", "Giungla", "Savana", "Steppa", "Tundra", "Taiga", "Palude", "Stagno", "Acquitrino", "Prato", "Campo", "Pascolo", "Coltivazione", "Vigneto", "Frutteto", "Orto", "Giardino", "Parco", "Aiuola", "Albero", "Arbusto", "Cespuglio", "Pianta", "Fiore", "Erba", "Muschio", "Lichene", "Fungo", "Radice", "Tronco", "Ramo", "Foglia", "Fiore", "Frutto", "Seme", "Pigna", "Ghianda", "Castagna", "Sasso", "Pietra", "Roccia", "Masso", "Ciottolo", "Ghiaia", "Sabbia", "Terra", "Fango", "Argilla", "Polvere", "Cenere", "Fuoco", "Fiamma", "Scintilla", "Brace", "Fumo", "Vapore", "Nuvola", "Nebbia", "Foschia", "Pioggia", "Goccia", "Temporale", "Fulmine", "Tuono", "Grandine", "Neve", "Fiocco", "Ghiaccio", "Ghiacciolo", "Valanga", "Vento", "Brezza", "Raffica", "Uragano", "Tornado", "Tromba d'aria", "Cielo", "Sole", "Luna", "Stella", "Pianeta", "Cometa", "Meteora", "Galassia", "Universo", "Città", "Paese", "Villaggio", "Borgo", "Quartiere", "Strada", "Via", "Viale", "Piazza", "Cortile", "Vicolo", "Incrocio", "Rotonda", "Semaforo", "Marciapiede", "Pista ciclabile", "Stazione", "Binario", "Treno", "Metropolitana", "Tram", "Autobus", "Fermata", "Aeroporto", "Aereo", "Elicottero", "Porto", "Molo", "Nave", "Barca", "Traghetto", "Ponte", "Viadotto", "Galleria", "Tunnel", "Diga", "Canale", "Ospedale", "Scuola", "Università", "Biblioteca", "Museo", "Teatro", "Cinema", "Stadio", "Palestra", "Piscina", "Chiesa", "Cattedrale", "Moschea", "Sinagoga", "Tempio", "Castello", "Palazzo", "Villa", "Casa", "Condominio", "Appartamento", "Negozio", "Supermercato", "Centro commerciale", "Ristorante", "Pizzeria", "Bar", "Pub", "Discoteca", "Hotel", "Albergo"
  ],
  corpo_abbigliamento: [
    "Testa", "Capelli", "Fronte", "Occhio", "Sopracciglio", "Ciglio", "Orecchio", "Naso", "Bocca", "Labbro", "Dente", "Lingua", "Mento", "Guancia", "Viso", "Collo", "Spalla", "Braccio", "Gomito", "Avambraccio", "Polso", "Mano", "Dito", "Pollice", "Indice", "Medio", "Anulare", "Mignolo", "Unghia", "Petto", "Seno", "Addome", "Pancia", "Ombelico", "Schiena", "Fianco", "Bacino", "Gluteo", "Gamba", "Coscia", "Ginocchio", "Polpaccio", "Caviglia", "Piede", "Tallone", "Pelle", "Osso", "Muscolo", "Sangue", "Cuore", "Polmone", "Stomaco", "Fegato", "Intestino", "Cervello", "Maglietta", "Camicia", "Maglione", "Felpa", "Giacca", "Cappotto", "Giubbotto", "Impermeabile", "Pantaloni", "Jeans", "Gonna", "Vestito", "Tuta", "Pigiama", "Mutande", "Slip", "Boxer", "Reggiseno", "Calzino", "Calza", "Collant", "Scarpa", "Stivale", "Sandalo", "Ciabatta", "Pantofola", "Cappello", "Berretto", "Sciarpa", "Guanto", "Cintura", "Cravatta", "Papillon", "Bretelle", "Orologio", "Bracciale", "Collana", "Anello", "Orecchino", "Spilla", "Occhiali", "Borsa", "Zaino", "Portafoglio", "Ombrello"
  ],
  mestieri_sport_hobby: [
    "Medico", "Infermiere", "Dentista", "Veterinario", "Farmacista", "Avvocato", "Giudice", "Poliziotto", "Carabiniere", "Pompiere", "Militare", "Insegnante", "Professore", "Studente", "Scienziato", "Ricercatore", "Ingegnere", "Architetto", "Geometra", "Muratore", "Elettricista", "Idraulico", "Falegname", "Fabbro", "Meccanico", "Carrozziere", "Elettrauto", "Gommista", "Benzinaio", "Autista", "Camionista", "Tassista", "Pilota", "Marinaio", "Cuoco", "Cameriere", "Pizzaiolo", "Pasticcere", "Panettiere", "Macellaio", "Pescivendolo", "Fruttivendolo", "Barista", "Commesso", "Cassiere", "Parrucchiere", "Estetista", "Sarto", "Calzolaio", "Giornalista", "Scrittore", "Attore", "Regista", "Musicista", "Cantante", "Ballerino", "Pittore", "Scultore", "Fotografo", "Atleta", "Allenatore", "Arbitro", "Contadino", "Allevatore", "Pescatore", "Impiegato", "Segretario", "Dirigente", "Imprenditore", "Operaio", "Calcio", "Pallacanestro", "Pallavolo", "Tennis", "Rugby", "Nuoto", "Atletica", "Ciclismo", "Motociclismo", "Automobilismo", "Ginnastica", "Scherma", "Pugilato", "Judo", "Karate", "Sci", "Snowboard", "Pattinaggio", "Equitazione", "Vela", "Canottaggio", "Golf", "Bocce", "Biliardo", "Freccette", "Scacchi", "Dama", "Carte", "Videogioco", "Lettura", "Scrittura", "Disegno", "Pittura", "Scultura", "Fotografia", "Musica", "Canto", "Ballo", "Cucina", "Giardinaggio", "Bricolage", "Collezionismo", "Modellismo", "Pesca", "Caccia", "Trekking", "Alpinismo", "Campeggio", "Viaggio"
  ],
  fantasia_astratto: [
    "Fantasma", "Vampiro", "Licantropo", "Zombi", "Strega", "Mago", "Fata", "Elfo", "Nano", "Orco", "Troll", "Drago", "Unicorno", "Pegaso", "Sirena", "Centauro", "Minotauro", "Ciclope", "Demone", "Angelo", "Dio", "Dea", "Mostro", "Alieno", "Astronave", "Ufo", "Robot", "Cyborg", "Macchina del tempo", "Teletrasporto", "Amore", "Odio", "Gioia", "Tristezza", "Rabbia", "Paura", "Sorpresa", "Disgusto", "Speranza", "Disperazione", "Pace", "Guerra", "Vita", "Morte", "Tempo", "Spazio", "Luce", "Buio", "Suono", "Silenzio", "Caldo", "Freddo", "Bene", "Male", "Vero", "Falso", "Sogno", "Incubo", "Magia", "Miracolo", "Mistero", "Segreto", "Illusione", "Follia", "Genio", "Fortuna", "Sfortuna", "Successo", "Fallimento", "Vittoria", "Sconfitta", "Libertà", "Prigionia", "Giustizia", "Ingiustizia", "Bellezza", "Bruttezza", "Verità", "Bugia", "Forza", "Debolezza", "Coraggio", "Viltà", "Saggezza", "Ignoranza"
  ]
};

// Flatten to a single massive array
let allWords = [];
for (const cat of Object.values(categories)) {
  allWords = allWords.concat(cat);
}

// Remove duplicates just in case
allWords = [...new Set(allWords)];

const outputPath = path.join(__dirname, 'src', 'data', 'disegnatore_words.json');
fs.writeFileSync(outputPath, JSON.stringify(allWords, null, 2));

console.log(`Generated ${allWords.length} unique words for Disegnatore!`);
